shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 5.0

planner_frequency: 0.1
planner_patience: 10.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true

recovery_behaviors:
  - name: 'conservative_clear'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_clear'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

conservative_clear:
  reset_distance: 0.5

aggressive_clear:
  reset_distance: 1.0

rotate_recovery:
  frequency: 10.0

NavfnROS:
  allow_unknown: true
